jobs:
  deploy:
    docker:
      - image: cimg/base
    steps:
      - attach_workspace:
          at: /
      - run: ls -lah /
orbs:
  hugo: circleci/hugo@0.2
version: 2.1
workflows:
  main:
    jobs:
      - hugo/build:
          html-proofer: false
          source: /
          version: '0.55'
      - deploy:
          filters:
            branches:
              only: main
          requires:
            - hugo/build